apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: vqdmyocpp-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/vqdmyocpp-java-quarkus-gitops